### ISSUE TITLE
Does it only work on py -files or how does it work?

### ISSUE THREAD

**Issue by thepenguinthatwants** [kiteco/vim-plugin#171]
Hi Kiteco fellas!

Quite exciting about kite and trying to  dive in as soon as possible. I am trying to configure this on Neovim. 

Right now using coc.vim on other autocompletions but thought about dedicating python autocompletions to  kite.

Are there any good tips on how to achieve this? If I enable autostart does it mean it mean it will collide with other autocompletes? Is it only enabled on py -files?

**Comment by airblade** [comment]
It's only enabled on `*.python` files.  It updates the `completeopt` option to work better with autocompletion if and only if you haven't already set the option yourself.

However I have just realised that it doesn't restore `completeopt` to its previous value when you leave a python buffer.  I'll update the plugin so it doesn't have any side-effects for non-python files.

It uses user-defined autocompletion (ctrl-x ctrl-u) instead of, say, omnicompletion.  I don't know how coc.vim works but you might well have to turn it off in python buffers so they don't clash with each other.

With that in mind, you should be able to use Kite in python buffers and coc.vim in all non-python buffers.

**Comment by airblade** [comment]
Commit a05b65f ensures the plugin doesn't have any side-effects when editing non-Python files.  This is in plugin version 1.0.31 (when editing a Python file you can check the version with `:echo kite#utils#plugin_version()`).

So Kite and coc.vim should co-exist happily – please post a message if not.
