### ISSUE TITLE
Error while processing kite#events

### ISSUE THREAD

**Issue by its-dhung** [kiteco/vim-plugin#180]
User reported that he's seeing an error on every keystroke:

>Problem still persists 
>My copilot version: 2.20190509.1 
>Nvim v0.3.4 
>I reinstall vim-plugin by copilot 
>Error message appears on every movement 

![image](https://user-images.githubusercontent.com/3752225/57739072-fa530f80-7666-11e9-9582-f8207c4d1a1b.png)

**Comment by airblade** [comment]
This is a weird error and not a [part of the code](https://github.com/kiteco/vim-plugin/blob/e6b1536c96cea02d660ad3db0d01d8d8902f9abe/autoload/kite/async.vim#L63) that I'd expect to cause problems.

The problem is occurring when the plugin tries to send an event to Kite asynchronously.

In this case neovim is unable to start a background job because, evidently, the argument list is too long.  The event payload contains the buffer contents, but only if it's [less than 1MB](https://github.com/kiteco/vim-plugin/blob/e6b1536c96cea02d660ad3db0d01d8d8902f9abe/autoload/kite/events.vim#L11-L17).  This seems to suggest that the user's `sh` shell (or OS?) limits the size on argument (or the whole list?) to less than 1MB, but I'm guessing here.

Please could you ask the user what OS they use and what `sh --version` gives?

**Comment by LarsMichelsen** [comment]
Same issue over here. Happens on Ubuntu 18.04 while sh points to dash 0.5.8-2.10. Changing to bash would make no difference, because we run into some kernel level limitations here.

One of the files affected by this issue has a size of 178904 bytes.

The limiting factor in this case is not the whole argument list, but the limit for a single argument (MAX_ARG_STRLEN). Have a look at https://serverfault.com/questions/163371/linux-command-line-character-limit for further information. Seems to be 131072 bytes per argument.

Enabling debug logging gives me the following line in kite-vim.log:

```
> /home/lm/.config/nvim/pack/kite/start/vim-plugin/lib/linux/kite-http --timeout 120ms --post --data '{"selections": [{"end": 57931, "start": 57931}], "source": "vim", "action": "selection", "editor_version": "NVIM v0.4.0-dev", "plugin_version": "1.0.32", "text": "(...)", "filename": "(..)"}' 'http://127.0.0.1:46624/clientapi/editor/event'
```

Pretty clear: The issue here is that the data is handed over to kite-http via command line arguments.
To really solve the problem the whole post data should be handed over via stdin to kite-http instead.

**Comment by airblade** [comment]
@LarsMichelsen Thanks for the useful info.

> To really solve the problem the whole post data should be handed over via stdin to kite-http instead.

I agree.

@jansorg This would be an easy change for the plugin – are you happy for me to go ahead?  Who would you like to update `kite-http`?

**Comment by jansorg** [comment]
@airblade Yes, this sounds like a good way to fix this. Please go ahead. If you're happy with Go then feel free to do the change as you could immediately test your change. If you preferred not to fix things in Go then I'd be happy to implement this.

**Comment by airblade** [comment]
Done in #185.
