### ISSUE TITLE
Kite conflicts with auto-pairs behavior

### ISSUE THREAD

**Issue by its-dhung** [kiteco/vim-plugin#207]
1. Install the auto-pairs plugin.
2. Start with the following buffer:
```python
print()
```
3. Position the cursor in between the `()` and delete the opening `(`.
4. With Kite enabled, only the `(` is deleted. If Kite were disabled, both `()` would be deleted automatically.

**Comment by airblade** [comment]
This is because both plugins map `<BS>` in insert mode, and Kite's mapping is overwriting auto-pairs'.

Kite's mapping is there to make `<BS>` trigger a fresh completion request when the completion menu is open.

I can see several options:

- Only add Kite's mapping when a completion has been triggered, and remove it once the completion is over.
- When adding Kite's mapping look for an existing one, save its right hand side, and call it if the completion menu isn't open.
- Do nothing: it's not uncommon for plugins to have conflicting mappings.

The first option seems like the neatest to me.  The second feels like a bit of a hack.

**Comment by airblade** [comment]
@its-dhung Do you want me to try to get the plugins to work together or just leave it?

**Comment by its-dhung** [comment]
@airblade I think we can just not have the editor plugin request completions on `<BS>`.

**Comment by adamsmith** [comment]
It may also be worth adding an automated regression test, if possible.

**Comment by airblade** [comment]
@its-dhung Reinvoking completions on `<BS>` originally came from Kite (though I can't lay my hands on a reference at the moment) so if you're happy for the plugin not to do it, that makes things much easier.
