### ISSUE TITLE
Error message when opening Vim

### ISSUE THREAD

**Issue by its-dhung** [kiteco/vim-plugin#224]
To reproduce, simply open Vim from the command line. You'll see this error message:

```
Error detected while processing VimEnter Auto commands for "*":
E492: Not an editor command: ++nested if &filetype !~# '^git' | call kite#onboarding#call() | endif
```

**Comment by airblade** [comment]
What version of Vim are you running?

**Comment by its-dhung** [comment]
8.0.1633

**Comment by jurginius** [comment]
Vim 8.0.1453 on Ubuntu 18.04.3 LTS

I have the issue in both vim and gvim, and it does not matter if I open a file, or an empty buffer. I get it all the time.

**Comment by airblade** [comment]
It turns out the `++nested` syntax was only introduced in [v8.1.1113](https://github.com/vim/vim/releases/tag/v8.1.1113).  Before then the syntax was `nested`.  Vim documents that `nested` is backward compatible...but not under the `autocmd-nested` section (which is where I had looked originally).  Instead it's under the `autocmd` section.

I pushed this straight to master, instead of opening a pull request, because the fix is clear.

**Comment by gusaiani** [comment]
Hello!

Tried Kite now to check out JS.

Got the error message this issue is about.

[My .vimrc](https://gist.github.com/gusaiani/82efd3fab81e416c6830782a408b5514)

vim 8.2.0700

Catalina 

Any suggestions, please?
Cheers

**Comment by airblade** [comment]
That's odd.

What does `:echo kite#utils#plugin_version()` give, please?

Also, does this work without error?

```viml
:if &filetype !~# '^git' | echom 'not git' | endif
```

**Comment by gusaiani** [comment]
It gives `not git`.

Yes, I did notice that after installing Kite for Vim, git-dependent libs like:

· fugitive
· vim-gitgutter

stopped working because they don't recognize the dir we're in as git.

Tried uninstalling Kite.
Same git issue

Then reinstalled Kite.
Same issue.

For the moment I'm stuck with a vim working worse than before.

Would appreciate any tips if you have them.

**Comment by airblade** [comment]
Hmm, I have vim-gitgutter and fugitive installed, along with Kite for Vim, and they all work.

What does `:echo kite#utils#plugin_version()` give?  I ask because I'm wondering whether you somehow have an old version of the plugin which uses `++nested`.  Although even if you did, it shouldn't cause an error because your version of Vim understands it.  Are you sure the error message is exactly the same as the one at the top of this issue?

Regarding reverting things, when you uninstalled Kite, did you also remove this plugin?  (I'm not sure whether the uninstaller does that.)  It'll be in the normal place for Vim's packages.

**Comment by gusaiani** [comment]
:echo kite#utils#plugin_version()
1.0.64

Yes, I uninstalled Kite's vim plugin.
Don't remember if I did it before or after uninstalling Kite itself.
I just went to ~/.vim and removed the pack dir. 
Kite's plugin was all there was in it.

**Comment by gusaiani** [comment]
@airblade, the full error message I get is this:

Error detected while processing VimEnter Autocommands for "*":
E117: Unknown function: kite#onboarding#call

**Comment by gusaiani** [comment]
Now I reinstall vim and all plugins from scratch — except Kite's plugin, this I did not add there.

Was able to get Vim back to normal, fugitive, gitgutter and all.

Copied pack dir into the fresh .vim dir.

Ran vim.

Got the #onboarding… error message.

Could no longer find git, back to the same errors I was getting.

**Comment by airblade** [comment]
That's really weird.

Once you've got past the errors, does `:KiteTutorial` execute without errors?  I'm wondering whether the function can't be found due to a load-order problem...although `VimEnter` is fired after all plugins are loaded, so the function should be available.

I wonder whether there's an old version of the plugin hanging around somewhere on your system.  You could try `:scriptnames` and look for any mention of kite and see where it's coming from.

I have no idea why this error would then prevent Vim from finding git.  All it does is check the filetype and call the function:

https://github.com/kiteco/vim-plugin/blob/ffb3500a5b018e6469385ec4b9080b392518f210/plugin/kite.vim#L83

**Comment by gusaiani** [comment]
Thank you @airblade.

I ran `:scriptnames` (after another full reinstall of vim and plugins…) and found no reference to Kite.

I will give up on Kite for the time being.

Just for fun I tried installing it in Atom and it was not working either.

I felt the whole process of installation, although I understand the attempt to make it "just work", ended up not feeling very good yet:

1. this issue we've been discussing
2. Kite opens all sorts of dialogs in vim, on editing .vimrc for example, offering tutorials. Feels intrusive
3. Feels intrusive the way it installs the plugin for a vim user. Too magic, no control. If it did work, I guess that would be great, but it's probably hard for a plugin to work in every vim installation like that.
4. 1 gig expanded file for Kite…didn't have the guts to check memory usage

I will try again in a few months.

Appreciate your very kind assistance and patience with the fact that I commented in a close issue with a different error message after all.

**Comment by airblade** [comment]
I think I would give up too :)

I can't think why `:scriptnames` wouldn't list an installed plugin.

Item 2 sounds like the onboarding, which is the thing triggered by `VimEnter` and `kite#onboarding#call()`.  The idea is that after you install Kite, you (re)start Vim so the plugin is loaded, and then it runs the onboarding.

I sympathise that it got in your way.  We haven't been able to think of a better time to show the tutorial though; if you have any suggestions we'd be happy to hear them.

It's weird that the tutorial ran, though, because your error indicated that Vim couldn't find the `kite#onboarding#call()` function.  And yet it did.  A proper Schrödinger's bug.

Item 3: I was overruled on that ;)

Sorry it didn't work out for you and thanks for giving it a try.

cc @jansorg
