### ISSUE TITLE
No action triggered by "Learn how to use Kite" 

### ISSUE THREAD

**Issue by jansorg** [kiteco/vim-plugin#255]
I stopped kited and remove ~/.kite.
Then, I started vim with the vim-plugin installed, using `vim test.txt`:

This nice dialog appeared, but nothing happened when I chose "Learn how to use Kite":
![Screenshot_012](https://user-images.githubusercontent.com/11473063/72896231-869df200-3d1f-11ea-84c1-2001ae1413da.png)

**Comment by airblade** [comment]
Maybe to do with Kite not running?

**Comment by airblade** [comment]
This is the expected behaviour in this case:

- When vim starts, the plugin tries to query kited for the tutorial file.
- If kited responds successfully, the plugin shows the tutorial in a new tab.
- Else the plugin shows that popup menu.  Pressing enter on "Learn how to use Kite" should open the Vim page on Kite's website in your browser.

Evidently something went wrong in handling your keypress.  Please could you let me know your vim version?  I'll look at vim's repo to see if there's a relevant bug(fix).

**Comment by jansorg** [comment]
@airblade Thank you for your feedback.
This is my Vim (Linux):
```text
VIM - Vi IMproved 8.2 (2019 Dec 12 kompiliert am Jan  7 2020 22:53:41)
Inklusive der Patches: 1-100
```

**Comment by airblade** [comment]
I'm using Vim 8.1.2234.  I can't see anything too relevant that changed in vim between our versions.

```
$ cd /path/to/vim/repo
$ git log v8.2.0100...v8.1.2234 | grep popup
```

It would be helpful to know whether Vim is receiving your keypress.  Right now I'm not sure whether it's not receiving the keypress, or receiving it but failing to open your browser.  Please could you try with this change, and look at the `:messages` afterwards:

```diff
diff --git i/autoload/kite/onboarding.vim w/autoload/kite/onboarding.vim
index 4313a10..6865484 100644
--- i/autoload/kite/onboarding.vim
+++ w/autoload/kite/onboarding.vim
@@ -60,6 +60,7 @@ endfunction
 
 
 function! s:handle_choice(index)
+  echom 'choice:' a:index
   if a:index == 0  " learn now
     call kite#utils#browse('https://help.kite.com/category/47-vim-integration')
   elseif a:index == 2  " hide forever
```

Also, you can force the dialog to appear with `:call kite#onboarding#call(1)`.

**Comment by jansorg** [comment]
This seems to be working here, now. I'm not sure why, but closing for now.
