### ISSUE TITLE
whenever I type, the curser go to the end of the line 

### ISSUE THREAD

**Issue by sisrfeng** [kiteco/vim-plugin#348]
Thank you for your nice work!
Whenever I type, the curser jumps to the end of the line.  I nearly can not code at all.
When I turn kite off  (in ~/.config/nvim/pack/kite/start/kite/plugin/kite.vim) , this problem disappears.
![image](https://user-images.githubusercontent.com/53520949/107368053-065d5100-6b1b-11eb-8047-12fc4e29c198.png)
While using jedi-vim, this problem does not exists.
This is part of my init.vim, which may cause the problem:
![image](https://user-images.githubusercontent.com/53520949/107368457-8aafd400-6b1b-11eb-9f32-40ae3be77ca3.png)

**Comment by airblade** [comment]
I'm sorry you're having this problem!

Is this when you type in insert mode or in normal mode?

Does the cursor still jump to the end of the line if the Kite plugin is the only one you have installed?

What's your vim version?

**Comment by sisrfeng** [comment]
> Is this when you type in insert mode or in normal mode?

insert mode 

![image](https://user-images.githubusercontent.com/53520949/107468927-d1e1a780-6ba3-11eb-8886-c22729421a93.png)

> Does the cursor still jump to the end of the line if the Kite plugin is the only one you have installed?

yes

If I delete this line in my init.nvim
` inoremap <C-E> <ESC>A`
No this problem

But I want to use <C-E>to jump to the line because it is faster then other methods(  my nvim does not react to END key)

**Comment by airblade** [comment]
This is what's happening:

- In insert mode, you type a letter.
- The plugin invokes completion (assuming `g:kite_auto_complete` is `1`, which is the default).
- The completion is asynchronous; before requesting completion candidates, the plugin [feeds in `<C-E>`](https://github.com/kiteco/vim-plugin/blob/351b709302f15799a31731d8ed4f40b05b35984b/autoload/kite/completion.vim#L109) to leave CTRL-X submode, so the user can invoke other completion methods in the meantime.
- Your mapping translates `<C-E>` to `<Esc>A` and sends your cursor to the end of the line.

The fix is to not have your mapping applied to the keys fed by the plugin.  Please can you try this patch?

```diff
diff --git i/autoload/kite/completion.vim w/autoload/kite/completion.vim
index 5f64280..3c105b7 100644
--- i/autoload/kite/completion.vim
+++ w/autoload/kite/completion.vim
@@ -400,7 +400,7 @@ endfunction
 " combo being applied in normal mode).  To avoid this we use the 'i' flag
 " which ensures the keys are processed immediately.
 function s:feedkeys(keys)
-  call feedkeys(a:keys, 'i')
+  call feedkeys(a:keys, 'in')
 endfunction
 ```

**Comment by sisrfeng** [comment]
Thx!!!
but I have many machine sharing the same dotfile, so changing autoload/kite/completion.vim in each machine seems not convinient.
I  prefer to delete this line in my init.nvim 

> inoremap <C-E> <ESC>A

**Comment by airblade** [comment]
Thanks for confirming it solves your problem.  We will roll this into the plugin itself (so you don't need to change anything at your end).
